### ISSUE TITLE
第4章__threaded_crawler.py__第18行开始的link问题

### ISSUE THREAD

**Issue by UesugiErii** [1040003585/WebScrapingWithPython#1]
当线程未达到最大线程时，会启动第18行的process_queue函数，但那个函数我不是很理解，能解释一下吗？

**Comment by UesugiErii** [comment]
当线程未达到最大线程使，会启动第18行的函数，但那个函数我不是很理解，能解释一下吗？

**Comment by 1040003585** [comment]
多个线程是同时都在运行的，这个你先学习多线程原理

**Comment by UesugiErii** [comment]
说实话问题提了好久，我自己已经解决了，麻烦了
